# Generated by Django 3.1.7 on 2021-09-08 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country1', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField(default=0)),
                ('Transdate', models.CharField(max_length=100)),
                ('Cfname', models.CharField(max_length=100)),
                ('Clname', models.CharField(max_length=100)),
                ('Ptype', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=40)),
                ('Qty', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(default=0)),
                ('Active', models.BooleanField()),
                ('Ccity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city12')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.country12')),
            ],
        ),
    ]
