# Generated by Django 2.2.11 on 2021-09-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Customer_ID',
        ),
    ]
